apiVersion: apps/v1
kind: Deployment
metadata: 
  name: java-api
  labels:
    app: java-api
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: java-api
    tags.datadoghq.com/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: java-api
        tags.datadoghq.version: "1.0.0"
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/java-api.logs: '[{"source":"java","service":"java-api"}]'
        admission.datadoghq.com/java-lib.version: v1.48.1
    spec:
      containers:
        - name: java-api
          image: iesodias/java-api:latest
          ports:
            - containerPort: 8081
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-api
  labels:
    app: java-api
spec:
  type: LoadBalancer
  selector:
    app: java-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: java-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

